### ISSUE TITLE
Using this library for text with word boundary

### ISSUE THREAD

**Issue by nirmals-workspace** [captn3m0/india-pincode-regex#3]
Can we use this to extract pincode from a line which has few words apart from pincode? If yes kindly explain how to do it...

**Comment by captn3m0** [comment]
Something like this works well:

```python
import re

regex = list()
f = open('regex.txt')
lines = f.readlines()
for line in lines:
    if (len(line) > 10):
        regex.append(re.compile(line[1:-2]))

def run_regexes(input_string):
    results = []
    # Apply each regex to the input string
    for r in regex:
        matches = re.findall(r, input_string)
        results.extend(matches)

    return results

for t in ['bangalore 560038', 'india 111111', 'my pincode is 244713']:
    results = run_regexes(t)
    print((t, results))
```

```bash
python t.py
('bangalore 560038', ['560038'])
('india 111111', [])
('my pincode is 244713', ['244713'])
```

The library currently does not support it, so this is adapted from https://github.com/captn3m0/india-pincode-regex/blob/master/src/pincode/__init__.py

**Comment by captn3m0** [comment]
@Nirmal-Data-Scientist Can you clarify which language you were trying to do this in? I've added support for a search method in v2 in JS/PHP/Ruby.

Python is still broken due to an issue I haven't figured out yet (#2), but I'll add it soon.

**Comment by nirmals-workspace** [comment]
I wanted to use it for a python based project but not needed now @captn3m0 as I have already completed the project using re library itself 2 weeks back...Glad you responded....Thank you so much...
